package bei7473p5254d69jcuat.tenyu.release1.global;

import java.util.*;

/**
 * @author exceptiontenyu@gmail.com
 *
 */
public enum Lang {
	ID,
	COUNT,
	EXIT,
	FQDN,
	TIMEZONE,
	LATENCY,
	IPADDR,
	IPADDR_INVALID,
	PORT,
	PORT_INVALID,
	CREATE_DATE,
	IMPRESSION,
	PRIORITY,
	DETAIL,
	FILE_SIZE,
	FILE_NAME,
	FILE_RELATIVE_PATH,
	FILE_EMPTY,
	FILE_ONLY,
	FILE_SELECT_NOTIFICATION,
	FILE_SELECT,
	DIR_SELECT,
	PARENT_DIR,
	ONLY_STATIC_FILE,
	ENTER_SEARCH,

	P2PEDGEBASE,
	P2PEDGEBASE_LATESTSCORE,
	P2PEDGEBASE_LASTCOMMUNICATION,
	P2PEDGEBASE_PROCESSORSCORETOTAL,
	P2PEDGEBASE_COMMONKEYEXCHANGESTATE,

	P2PEDGE,
	P2PEDGE_CONNECTIONCOUNT,
	P2PEDGE_CONNECTIONFAILEDCOUNT,
	P2PEDGE_CREATEDATE,
	P2PEDGE_INTRODUCESCORE,
	P2PEDGE_LATENCY,

	P2PNODE,

	COMMONKEYINFO_COMMONKEY,
	COMMONKEYINFO,

	USERADDR,

	STANDARD_USER,
	CREATOR_USER,
	ADMIN_USER,

	OLD_OBJECT_AT_UPDATE,

	EXCEPTION,
	NOT_FOUND,
	NAME_ALREADY_EXISTS,

	ID_EMPTY,
	ID_INVALID,
	ID_NOT_FOUND,

	OBJECTIVITY,
	OBJECTIVITY_CORE,
	OBJECTIVITY_CORE_WALLET,
	OBJECTIVITY_CORE_DISTRIBUTEDTRADABLE_IDGENERATOR,
	OBJECTIVITY_CORE_HISTORYINDEX,
	OBJECTIVITY_CORE_LATESTACCEPTED_PLATFORMSOFTWARE,
	OBJECTIVITY_CORE_MANAGERLIST,
	OBJECTIVITY_CORE_CONFIG,
	OBJECTIVITY_CORE_CONFIG_ACTIVATE_PERIOD,
	OBJECTIVITY_CORE_CONFIG_HISTORYINDEXDAYROUGH,
	OBJECTIVITY_CORE_CONFIG_HISTORYINDEXMILLIS,
	OBJECTIVITY_CORE_CONFIG_SHARINGRATE,
	OBJECTIVITY_CORE_CONFIG_USERREGISTRATIONACTIVATE,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_USERMESSAGELIST_APPLYSIZEMAX,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_BANDWIDTHMIN,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_MESSAGESIZEMAX,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_SERVERCOUNTMAX,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_USERMESSAGELIST_SIZEMAX,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_USERMESSAGELISTCOUNTMAX,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_USERMESSAGELIST_COUNTMAX_ADMIN,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_USERMESSAGELIST_COUNTMAX_AUTHOR,
	OBJECTIVITY_CORE_CONFIG_LOADSETTING_USERMESSAGELIST_COUNTMAX_STANDARD,

	SUBJECTIVITY,

	NOT_YOURS,
	NOT_ADMINISTRATOR,
	ONLY_USER,
	ONLY_ADMINISTRATOR,
	ONLY_51PER_ADMINISTRATOR,
	ONLY_ME,
	ONLY_REGISTERER,

	KEY_GENERATION_WAIT_1MINUTE,

	NATURALITY_CATEGORY_NAME,
	NATURALITY_GUI_NAME,
	//NATURALITY_NAME,
	//NATURALITY_EXPLANATION,
	NATURALITY_NAME_EMPTY,
	NATURALITY_EXPLANATION_EMPTY,

	SOCIALITY_GUI_NAME,

	PASSWORD_ENCRYPT_TITLE,
	PASSWORD_DECRYPT_TITLE,
	PASSWORD_HEADER,
	PASSWORD,
	PASSWORD_KEY_SETUP_FAILED,
	PASSWORD_NOT_EQUAL,
	PASSWORD_CONFIRM,

	SECRETKEYPASSWORD,

	NECESSARY,
	CHOICE_ONE,

	OUTLINE,
	SHORTCUT_KEY,
	SHORTCUT_KEY_CONTENT,

	COMMUNICATING,
	PROCESSING,
	SUCCESS,
	FAILED,

	NEIGHBOR,
	NEIGHBOR_LIST,
	NEIGHBOR_MANUAL_ADD,
	NEIGHBOR_MANUAL_ADD_EXPLANATION,
	NEIGHBOR_DONT_REMOVE_AUTOMATICALLY,
	NEIGHBOR_IMPRESSION_CHANGED,
	NEIGHBOR_MANUAL_DELETE,
	NEIGHBOR_MANUAL_DELETE_EMPTY,

	USER,
	USER_NAME,
	USER_NO_NEIGHBOR,
	USER_ID,
	USER_INTRODUCER,
	USER_ADDITIONALSETTING,
	USER_ADDITIONALSETTING_KEY,
	USER_ADDITIONALSETTING_VALUE,
	USER_TENYU_MANAGER_MEMO,
	NATURALITY_EXPLANATION_PROMPT,
	USER_NO_FQDN,

	USER_MESSAGE_SERVER,

	TITLE,
	LAUNCH_LOG,
	RUNLEVEL_WARN,
	RUNLEVEL {
		@Override
		public String toString() {
			return Glb.getFile().getConfFile() + ": "
					+ messages.getProperty(name());
		}
	},
	START_TEXTAREA_LOG,
	P2PPORT,
	GAMEPORT,
	TENYUTALKPORT,
	SERVERMODE,
	LOCALIPCPORT,
	NEIGHBOR_WHITELIST,
	BIG_STORAGE,
	FQDN_CONF,
	PHYSICAL_CORE_NUMBER,
	NODE_NUMBER,
	NODE_IDENTIFIER,
	NODE_IDENTIFIER_USERID,
	NODE_IDENTIFIER_NODENUMBER,
	DYNAMICFILES_DIR,
	RSA_GENERATE_ERROR,
	START_SIGN_KEY,
	START_GENERATE_KEY,
	NO_IPADDRESS,
	FAILED_TO_CREATE_FILE,
	FAILED_TO_DELETE_FILE,
	NEIGHBORS,
	INVALID_RESULT,
	SUBNODE_SUBJECTIVITY,

	CONF,
	CONF_PC_KEY_PAIR,
	CONF_MOBILE_KEY_PAIR,
	CONF_OFF_KEY_PAIR,
	CONF_OFF_SIGN_BY_MOB,
	CONF_OFF_SIGN_BY_PC,
	CONF_MOBILE_SIGN,
	CONF_PC_SIGN,

	DB_CATCHUP_COMPLETED,
	DB_CATCHUP_UNCOMPLETED,
	DB_CATCHUP_NO_RESPONSE,

	STANDARDRESPONSE_RESULT,
	STANDARDRESPONSE_RESULT_SUCCESS,
	STANDARDRESPONSE_RESULT_FAIL,
	STANDARDRESPONSE_RESULT_DEFAULT,
	STANDARDRESPONSE_RESULT_OVER_SIZE,

	SEARCH_PROMPT,
	SEARCH_NOT_FOUND,
	SEARCH_RESULT,

	NATURALITY_SEARCH,
	USER_SEARCH,
	USER_COUNT,

	MANAGER_VOTE,

	MATERIAL_FUNCTIONS,
	MATERIALRELATION,
	MATERIALRELATION_REGISTER,
	MATERIALRELATION_UPDATE,
	MATERIALRELATION_DELETE,
	MATERIALRELATION_SEARCH,
	MATERIALRELATION_REFTOMATERIALID_ADD,

	MATERIAL,
	MATERIAL_FILE,
	MATERIAL_REGISTER_BATCH,
	MATERIAL_REGISTER_NOTIFICATION,
	MATERIAL_DELETE,
	MATERIAL_UPDATE,
	MATERIAL_UPDATE_BATCH,
	MATERIAL_UPDATE_NOTIFICATION,
	MATERIAL_SEARCH,
	MATERIAL_EXP_PROMPT,
	MATERIAL_LIST,
	MATERIAL_LIST_ADD,
	USER_LIMITATION,
	USER_LIMITATION_PROMPT,
	USER_LIMITATION_ADD,
	USER_LIMITATION_CLEAR,
	USER_LIMITATION_REMOVE_LAST,
	USER_LIMITATION_USE,

	ROLE,
	ROLE_SYSTEM,
	ROLE_ADMINS,

	TABLEVIEW_REMOVE_SELECTED,

	AVATAR,
	AVATAR_REGISTER,
	AVATAR_DELETE,
	AVATAR_UPDATE,
	AVATAR_SEARCH,
	AVATAR_NAME_PROMPT,
	AVATAR_EXP_PROMPT,
	AVATAR_NAME,

	STYLE,
	STYLE_NAME_PROMPT,
	STYLE_EXP_PROMPT,
	STYLE_REGISTER,
	STYLE_DELETE,
	STYLE_UPDATE,
	STYLE_SEARCH,
	STYLE_NAME,

	GAME,
	GAME_MANAGER,
	GAME_FILE_UPDATE_COUNT,

	GAME_REFERENCE,
	GAME_REFERENCE_GAME_ID,
	GAME_REFERENCE_TYPE,

	GAMEPLAY,
	GAMEPLAY_RATINGGAME,
	GAMEPLAY_RATINGGAME_SEARCH,
	GAMEPLAY_RATINGGAME_SEARCH_SINGLE,
	GAMEPLAY_RATINGGAME_SEARCH_TEAM,
	GAMEPLAY_RATINGGAME_APPLICATE_SINGLE,
	GAMEPLAY_RATINGGAME_ADD_TEAM,
	GAMEPLAY_RATINGGAME_PERTICIPATE_TEAM,
	GAMEPLAY_RATINGGAME_RESET_TEAM,
	GAMEPLAY_RATINGGAME_TEAM_MATCHING,
	GAMEPLAY_RATINGGAME_TEAM_NAME_SEARCH,
	GAMEPLAY_RATINGGAME_LAUNCH,
	GAMEPLAY_STATICGAME,
	GAMEPLAY_STATICGAME_LAUNCH,
	GAMEPLAY_MATCHING_TEAM,
	GAMEPLAY_MATCHING_TEAM_GAMEREF,
	GAMEPLAY_MATCHING_TEAM_TYPE,
	GAMEPLAY_MATCHING_TEAM_STATE,
	GAMEPLAY_MATCHING_TEAM_CLASSNAME,
	GAMEPLAY_MATCHING_TEAM_TEAMCLASSID,
	GAMEPLAY_MATCHING_TEAM_MEMBERS,
	GAMEPLAY_MATCHING_TEAM_MEMBER,
	GAMEPLAY_MATCHING_TEAM_NAME,
	GAMEPLAY_MATCHING_TEAM_ADMIN,
	GAMEPLAY_MATCHING_TEAM_PASSWORD,

	PACE_LIMIT_AMOUNT,

	RATINGGAME,
	RATINGGAME_REGISTER,
	RATINGGAME_UPDATE,
	RATINGGAME_DELETE,
	RATINGGAME_SEARCH,
	RATINGGAME_CONFLICT_MATCH_LIST,
	RATINGGAME_MATCH_SEARCH_SINGLE,
	RATINGGAME_MATCH_SEARCH_TEAM,

	STATICGAME,
	STATICGAME_REGISTER,
	STATICGAME_UPDATE,
	STATICGAME_DELETE,
	STATICGAME_SEARCH,

	REGISTER,
	DELETE,
	UPDATE,
	SEARCH,

	USER_SECURE,
	USER_INVITER,
	USER_REGISTRATION,
	USER_REGISTRATION_INTRODUCE,
	USER_REGISTRATION_INTRODUCE_OFFER,
	USER_REGISTRATION_INTRODUCE_OFFER_DENIED,
	USER_REGISTRATION_INTRODUCE_OFFER_ACCEPTED,
	USER_REGISTRATION_INTRODUCE_EXPLANATION_PROMPT,
	USER_REGISTRATION_INTRODUCE_OK,
	USER_REGISTRATION_INTRODUCE_CANCEL,
	USER_REGISTRATION_INTRODUCE_OFFERED,
	USER_REGISTRATION_INTRODUCE_EMPTY,
	USER_REGISTRATION_INTRODUCE_FATAL_ERROR,
	USER_REGISTRATION_INTRODUCE_SEND_FAILED,
	USER_REGISTRATION_INTRODUCE_INVALID_DATA,
	USER_REGISTRATION_INTRODUCE_OFFER_EMPTY,

	USER_UPDATE,
	USER_DELETE,
	USER_BAN_SIMPLE,
	USER_KEY_UPDATE,
	USER_EDGE_UPDATE,

	USER_AVATAR_CONFIG,
	USER_AVATAR_CONFIG_ADD,
	USER_AVATAR_CONFIG_UP,
	USER_AVATAR_CONFIG_DOWN,
	USER_AVATAR_CONFIG_DELETE,
	USER_AVATAR_CONFIG_OUT_OF_RANGE,

	USER_TIMEZONE_SET_CURRENT,

	SERVER_IS_UNKNOWN_USER,

	SEND_MONEY,
	OTHER,
	OTHER_SECRETKEYPASSWORD_CHANGE,
	OTHER_INVENTORPROVEMENTPASSWORD,

	DELAYRUN,
	DELAYRUN_RUNHISTORYINDEX,
	DELAYRUN_REGISTERHISTORYINDEX,
	DELAYRUN_PROC,

	RATINGGAMEMATCHPROC_MATCHREFERENCE,

	REGEX_AND_SELECT,
	REGEX_AND_SELECT_REGEX,
	REGEX_AND_SELECT_SKIP,
	REGEX_AND_SELECT_GROUPINDEX,

	URLPROVEMENT_REGEX,
	URLPROVEMENT_REGEX_FQDNS,
	URLPROVEMENT_REGEX_FQDN,
	URLPROVEMENT_REGEX_URLREGEX,
	URLPROVEMENT_REGEX_CONTENTREGEXES,

	USER_EDGE_ACCESSDATE,
	USER_EDGE_CONNECTIONFAILEDCOUNT,
	USER_EDGE_CREATEDATE,
	USER_EDGE_RECEIVE_KEY,
	USER_EDGE_SEND_KEY,

	ERROR_EMPTY,
	ERROR_NOT_EMPTY,
	ERROR_NOT_EQUAL,
	ERROR_INVALID,
	ERROR_INVALID_CLASS,
	ERROR_INVALID_REFERENCE,
	ERROR_TRIM,
	ERROR_TOO_LONG,
	ERROR_TOO_SHORT,
	ERROR_TOO_BIG,
	ERROR_TOO_LITTLE,
	ERROR_TOO_MANY,
	ERROR_TOO_FEW,
	ERROR_FIRST_CHARACTER_SHOULD_ALPHABET,
	ERROR_PARENT_PATH,
	ERROR_SPECIAL_CHARACTERS,
	ERROR_CONTROL_CHARACTERS,
	ERROR_NOT_NORMALIZED,
	ERROR_UNALTERABLE,

	/**
	 * 自分のIDやサブインデックスについて
	 * DBに存在すべき文脈で存在しない場合
	 *
	 * ERROR_DB_NOTFOUND_REFERENCEは何らかのLong IDについて
	 * validateReferenceにおいて問題が発見された場合に使用されるが、
	 * こちらはサブインデックス全般なのでString name等にも使用される。
	 */
	ERROR_DB_NOTFOUND,
	/**
	 * 他モデルを参照している時の参照
	 * validateReferenceで使用される
	 */
	ERROR_DB_NOTFOUND_REFERENCE,
	ERROR_DB_EXIST,

	ERROR_SOCIALITY_BANNED,
	ERROR_NOT_DEFAULT,

	ERROR_NO_INVITER,
	ERROR_SOCIALITY_TYPE_COOPERATIVE_ACCOUNT_AND_INVALID_ADMINISTRATOR,

	ERROR_NOT_EQUAL_CONFIRMATION,

	OBJECT,
	IDOBJECT_RECYCLE_ID,
	OBJECTIVITYOBJECT_REGISTERER,
	OBJECTIVITYOBJECT_REGISTERER_NAME,
	OBJECTIVITYOBJECT_ADMINISTRATOR,
	OBJECTIVITYOBJECT_ADMINISTRATOR_NAME,
	OBJECTIVITYOBJECT_ID_BY_ADMINISTRATOR,
	OBJECTIVITYOBJECT_SEARCH,
	NATURALITY_NAME,
	NATURALITY_EXPLANATION,
	MATERIALRELATION_AVATAR_ID,
	MATERIALRELATION_STYLE_ID,
	MATERIALRELATION_REFTOMATERIALID,
	MATERIALRELATION_REFTOMATERIALID_REFNAME,
	MATERIALRELATION_REFTOMATERIALID_MATERIALID,
	MATERIALRELATION_ID_BY_AVATAR,
	FREEKVS_KEY,
	FREEKVS_KEY_USERPREFIX,
	FREEKVS_VALUE,
	SOCIALITY,
	SOCIALITY_NATURALITY_CONCRETE_ID,
	SOCIALITY_NODETYPE,
	SOCIALITY_WALLET,
	SOCIALITY_WALLET_BALANCE,
	SOCIALITY_WALLET_LIMIT,
	SOCIALITY_WALLET_SENDMONEYLOGS,
	SOCIALITY_WALLET_SENDMONEYLOG_AMOUNT,
	SOCIALITY_WALLET_SENDMONEYLOG_HISTORYINDEX,
	SOCIALITY_BANNED,
	SOCIALITY_FLOW_FROM_COOPERATIVEACCOUNT,
	SOCIALITY_BLACKLIST,
	SOCIALITY_EDGES,
	SOCIALITY_EDGELOG_FROM_SOCIALITYID,
	SOCIALITY_EDGELOG_TO_SOCIALITYID,
	SOCIALITY_EDGELOG_ADD,
	SOCIALITY_EDGELOG_COMMENT,
	SOCIALITY_EDGELOG_CRUDTYPE,
	SOCIALITY_INCOMESHARING_SENDERSOCIALITYID,
	SOCIALITY_INCOMESHARING_RECEIVERSOCIALITYID,
	SOCIALITY_INCOMESHARING_SHARINGNUMBER,

	EDGEMANAGER_EDGES,
	EDGEMANAGER_EDGES_SOCIALITY_ID,
	EDGEMANAGER_CHANGEAMOUNT,
	EDGEMANAGER_EDGE,

	EDGE_DESTSOCIALITYID,
	EDGE_TYPE,
	EDGE_WEIGHT,

	P2PDEFENSE,
	USERMESSAGELIST_MESSAGES,
	USERMESSAGELIST_APPLYSIZETOTAL,
	USERMESSAGELIST_SIZETOTAL,
	USERMESSAGELIST_HISTORYINDEX,
	USERMESSAGELISTHASH_HASH,
	USERMESSAGELISTHASH_HISTORYINDEX,
	RATINGGAME_TEAM_USEPASSWORD,
	RATINGGAME_TEAM_CURRENT_MEMBER_COUNT,
	RATINGGAME_TEAMCLASS,
	RATINGGAME_TEAMCLASS_ID,
	RATINGGAME_TEAMCLASS_NAME,
	RATINGGAME_TEAMCLASS_MEMBER_COUNT,
	RATINGGAME_TEAMCLASS_REGISTER,
	RATINGGAME_MATCH,
	RATINGGAME_MATCH_PROCESSED,
	RATINGGAME_MATCH_CONFLICT,
	RATINGGAME_MATCH_MATCHEDTEAMS,
	RATINGGAME_MATCH_CREATEDATE,
	RATINGGAME_MATCH_TYPE,
	RATINGGAME_MATCH_HOST,
	RATINGGAME_MATCH_ENOUGHRANDOM,
	RATINGGAME_MATCH_RATINGGAME_ID,
	RATINGGAME_MATCH_PLAYERUSERIDS,
	RATINGGAME_MATCH_PLAYERUSERID,
	RATINGGAME_MATCH_REPORTS,
	RATINGGAME_MATCH_REPORT,
	RATINGGAME_MATCH_REPORT_KEYTYPE,
	RATINGGAME_MATCH_REPORT_MATCHID,
	RATINGGAME_MATCH_REPORT_PLAYERUSERID,
	RATINGGAME_MATCH_REPORT_RANKING,
	RATINGGAME_MATCH_REPORT_REPLAYFILEHASH,
	RATINGGAME_MATCH_REPORT_RESULT,
	RATINGGAME_MATCH_REPORT_SIGN,
	RATINGGAME_MATCH_REPORT_PLAYERCOMMENT,
	RATINGGAME_MATCH_REPORT_GAMECLIENTCOMMENT,
	TENYU_FILE_PATH,
	TENYU_FILE_SIZE,
	TENYU_FILE_HASH,
	TENYU_FILE_KIND,
	GAME_CLIENTFILES,
	GAME_EXECUTABLELAUNCHERINDEX,
	GAME_VALIDATIONEXECUTABLEINDEX,
	GAME_TITLEIMAGEINDEX,
	GAME_CLIENTFILES_ADD,
	STATICGAME_SERVERS,
	STATICGAME_SERVER,
	DISTRIBUTEDTRADABLE_CONFIRMED_OWNER,
	DISTRIBUTEDTRADABLE_ID_BY_CONFIRMEDUSER,
	DISTRIBUTEDTRADABLE_FIRST_OWNER,
	UPLOADFILE,
	UPLOADFILE_FILECORE,
	UPLOADFILE_FILESIZE,
	UPLOADFILE_FILEHASH,
	TENYU_MANAGERLIST,
	TENYU_MANAGER_POWER,
	TENYU_MANAGER_USERID,
	TENYU_PLATFORM_FILE,
	TENYU_PLATFORM_FILES,
	TENYU_PLATFORM_FILE_RELEASE,
	MATERIAL_USER_LIMITATION,
	AVATAR_USER_LIMITATION,
	USER_MOBILEKEY,
	USER_PCKEY,
	USER_OFFKEY,
	USER_AVATAR,
	USER_HISTORYINDEX,
	USER_NODENUMBER,
	USER_NODENUMBER_TO_ADDR,
	USER_TIMEZONE,
	USER_CREATEDATE,
	USER_CREATE_HISTORYINDEX,
	WEB_URL,
	WEB_URL_REGISTRATION,
	GAMEITEMCLASS_GAMEREF,
	GAMESTATEBYUSER_USER_ID,
	GAMESTATEBYUSER_GAMEREF,
	GAMESTATEBYUSER_GAMEID_AND_USERID,
	GAMESTATEBYUSER_ID_BY_GAMEID_AND_USERID,
	GAMESTATEBYUSER_PAYAMOUNT,
	GAMESTATEBYUSER_EQUIPMENTS,
	GAMESTATEBYUSER_MATERIALS,
	RATINGGAME_COUNT_BY_TEAMCLASS,
	RATINGGAMESTATEBYUSER,
	RATINGGAMESTATEBYUSER_GAMEREFERENCE,
	RATINGGAMESTATEBYUSER_TEAM_RATING,
	RATINGGAMESTATEBYUSER_SINGLE_RATING,
	RATINGGAMESTATEBYUSER_MATCHCOUNT_TEAM,
	RATINGGAMESTATEBYUSER_MATCHCOUNT_SINGLE,
	STATICGAMESTATEBYUSER_GAMEREFERENCE,
	GAMEMATERIAL_INSTANCE,
	GAMEMATERIAL_INSTANCE_MATERIAL_ID,
	GAMEMATERIAL_INSTANCE_AMOUNT,
	GAMEEQUIPMENT_INSTANCE_EQUIPMENT_ID,
	GAMEEQUIPMENT_INSTANCE_STRENGTHNING,
	GAMEEQUIPMENT_INSTANCE_OPTION,
	GAMEEQUIPMENT_INSTANCE_OPTIONS,
	GAMEEQUIPMENT_OPTIONSMAX,

	AGENDA_VOTES,
	AGENDA_STATUS,
	AGENDA_CONTENT,
	AGENDA_TRUE_THRESHOLD,
	AGENDA_FALSE_THRESHOLD,
	AGENDA_END_HISTORYINDEX,
	AGENDA_START_HISTORYINDEX,
	AGENDA_CREATEDATE,

	AGENDA_PROC_AGENDA_ID,

	AGENDA_POLICY,
	AGENDA_POLICY_ADDED,
	AGENDA_POLICY_CONTENT,
	AGENDA_PHYSICALDELETE,
	AGENDA_PHYSICALDELETE_BYSTORE_ID,
	AGENDA_PHYSICALDELETE_BYSTORE_IDS,
	AGENDA_PHYSICALDELETE_DELETES,
	AGENDA_PHYSICALDELETE_BYSTORE_STORENAME,
	AGENDA_CONFIG,
	AGENDA_BAN,
	AGENDA_BAN_IDS,
	AGENDA_BAN_IDS_USER,
	AGENDA_BAN_IDS_USER_CHAIN,
	AGENDA_VERSIONUP,
	AGENDA_URLPROVEMENT_REGEX_CREATE,
	AGENDA_URLPROVEMENT_REGEX_CREATE_URLPROVEMENT_REGEX,
	AGENDA_URLPROVEMENT_REGEX_UPDATE,
	AGENDA_URLPROVEMENT_REGEX_UPDATE_URLPROVEMENT_REGEX,
	AGENDA_URLPROVEMENT_REGEX_DELETE,
	AGENDA_URLPROVEMENT_REGEX_DELETE_ID,
	AGENDA_SOCIALITYCHANGE,
	AGENDA_SOCIALITYCHANGE_NEWADMINUSERID,
	AGENDA_SOCIALITYCHANGE_SOCIALITYID,

	ERROR_FILE_NOT_FOUND,
	ERROR_DUPLICATE,
	ERROR_FAILED_TO_MKDIR,
	ERROR_FAILED_TO_FILE_MOVE,

	DISTRIBUTEDVOTE_CHOICE_NAME,
	DISTRIBUTEDVOTE_CHOICE_OPTION_LONG,
	DISTRIBUTEDVOTE_CHOICE_OPTION2,
	DISTRIBUTEDVOTE_VOTEVALUE_DISTRIBUTEDVOTE_ID,
	DISTRIBUTEDVOTE_POWERVOTE_POWERS,
	DISTRIBUTEDVOTE_CHOICES,
	DISTRIBUTEDVOTE_SYSTEM,
	DISTRIBUTEDVOTE_TYPE,
	DISTRIBUTEDVOTE_SCHEDULE,
	DISTRIBUTEDVOTE_RESULT,
	DISTRIBUTEDVOTE_RESULT_DISTRIBUTEDVOTE_ID,
	DISTRIBUTEDVOTE_RESULT_DISTRIBUTEDVOTE_ID_AND_STARTHISTORYINDEX,
	DISTRIBUTEDVOTE_RESULT_STARTHISTORYINDEX,
	DISTRIBUTEDVOTE_RESULT_MYFIRSTVOTE,
	DISTRIBUTEDVOTE_RESULT_NEIGHBORSVOTES,
	DISTRIBUTEDVOTE_RESULT_MAJORITY,
	DISTRIBUTEDVOTE_RESULT_FINISHED,
	DISTRIBUTEDVOTE_RESULTS,

	CHOICE_NAME,
	CHOICE_OPTION,
	CHOICE_OPTION2, VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_EDITION, VERSION_LEVEL, VERSION_PLATFORMS,VERSION_PLATFORM,;
	private static Properties messages = null;
	static {
		//messagesは初期化手順が問題になる
		//普通に書いているとFileやConfに依存しやすいが、
		//場合によってそれらに書くべきものも独自に持つべき

		//最初にOSの言語設定に従って読み込みを試みる
		String path = Glb.getFile().getLogMessagePropertyFilePath(
				Locale.getDefault().getLanguage());
		try {
			messages = Glb.getUtil().loadProperties(path,
					Glb.getConst().getCharset(), Glb.getLogger());
		} catch (Exception e) {
		}

		//失敗すれば英語ファイルを読み込む
		if (messages == null) {
			try {
				path = Glb.getFile().getLogMessagePropertyFilePath(
						Locale.ENGLISH.getLanguage());
				messages = Glb.getUtil().loadProperties(path,
						Glb.getConst().getCharset(), Glb.getLogger());
			} catch (Exception e) {

			}
		}

		//最悪messages=nullでも最低限の動作は可能
	}

	@Override
	public String toString() {
		String s = null;
		try {
			if (messages != null)
				s = messages.getProperty(name());
		} catch (Exception e) {
			Glb.debug(e);
		}
		if (s == null)
			s = name();
		return s;
	}
}